source 'https://rubygems.org'
gem 'sinatra'
gem 'tux'
gem 'haml'
gem 'sass'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'coffee-filter'
gem 'bson_ext'
gem 'mongo_mapper'
gem 'mongomapper_id2'
